
# Conmutador de versi√≥n HTTP para el cliente del conector (default 1_1)
paymentsportal:
  connector:
    http-version: ${PAYMENTSPORTAL_CONNECTOR_HTTP_VERSION:1_1}
app:
  security:
    enabled: false
# SSL para clientes HTTPS (conectores TMF676)
tmf676:
  ssl:
    trust-store: classpath:coremgmt-truststore.jks
    trust-store-password: ${PAYMENTS_SECRET:?}
    trust-store-type: JKS
